name: CI Build
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    
# Checks if any concurrent jobs under the same pull request or branch are being executed
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: build syscalls-bumper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout libs ⤵️
        uses: actions/checkout@v4
        with:
          repository: khulnasoft/libs
          path: ${{ github.workspace }}/libs
          
      - name: Checkout syscalls-bumper repo ⤵️
        uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}/syscalls-bumper
    
      - name: Install deps ⛓️
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends golang ca-certificates cmake build-essential clang-14 llvm-14 pkg-config autoconf automake libtool libelf-dev libcap-dev linux-headers-$(uname -r)
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-14 90
          sudo update-alternatives --install /usr/bin/llvm-strip llvm-strip /usr/bin/llvm-strip-14 90
          sudo update-alternatives --install /usr/bin/llc llc /usr/bin/llc-14 90

      - name: Build syscalls-bumper
        working-directory: ${{ github.workspace }}/syscalls-bumper
        run: make build
          
      - name: Execute syscalls-bumper against local libs
        working-directory: ${{ github.workspace }}/syscalls-bumper
        run: ./build/syscalls-bumper --repo-root $GITHUB_WORKSPACE/libs  --overwrite
        
      - name: Generate diff
        working-directory: ${{ github.workspace }}/libs
        run: git diff > syscalls-bumper.diff

      - name: Upload diff tarball
        uses: actions/upload-artifact@v3
        with:
          name: libs-diff
          path: ${{ github.workspace }}/libs/syscalls-bumper.diff

      - name: Test scap-open build
        working-directory: ${{ github.workspace }}/libs
        run: |
          mkdir build && cd build
          cmake -DUSE_BUNDLED_DEPS=On -DBUILD_BPF=On -DBUILD_LIBSCAP_MODERN_BPF=On -DBUILD_LIBSCAP_GVISOR=Off ../
          make driver
          make bpf
          make scap-open -j8
